# mypy: ignore-errors
from .definitions import *
from _typeshed import Incomplete

logger: Incomplete
duoStatusRequest: str
duoCommand: str
duoWeatherConfig: str
duoWeatherWriteConfig: str
duoSetTime: str

def merge_dicts(*dict_args): ...
def DoTrigger(*args) -> None: ...
def RemoveInternalTimer(*args) -> None: ...
def DUOFERN_DecodeWeatherSensorConfig(*args) -> None: ...

class Duofern:
    asyncio: Incomplete
    modules: Incomplete
    ignore_devices: Incomplete
    send_hook: Incomplete
    changes_callback: Incomplete
    def __init__(self, send_hook: Incomplete | None = ..., asyncio: bool = ..., changes_callback: Incomplete | None = ...) -> None: ...
    def add_device(self, code, name: Incomplete | None = ...) -> None: ...
    def del_device(self, code, name: Incomplete | None = ...) -> None: ...
    def update_state(self, code, key, value, trigger: Incomplete | None = ..., channel: int = ...): ...
    def delete_state(self, code, key, channel: int = ...): ...
    def get_state(self, code, key, channel: Incomplete | None = ..., default: Incomplete | None = ...): ...
    def parse(self, msg): ...
    def send(self, cmd) -> None: ...
    def set(self, code, cmd, *args, channel: int = ...): ...
